### ISSUE TITLE
Problems with sample and cell type assignment; Demuxlet metadata not matching

### ISSUE THREAD

**Issue by Flope** [dtm2451/ProgressiveHematopoiesis#1]
Hi Daniel, 

I was trying to access your data from your cell report paper
https://figshare.com/projects/Single-cell_mapping_of_progressive_fetal-to-adult_transition_in_human_hematopoiesis/76143

I am interested in CD8 adult and newborns cells. 
I downloaded the data "naive T cell single-cell RNA-seq, raw counts and annotation"

and I am following the R code:
scRNAseq_naiveTcells.Rmd

I am able to open the files and start processing them. 
However, the metadata cell type classification in the code does not seem to match the one in the count files. 
This is the code:
```
# Add Age
Tcells@meta.data$age <- "unknown"
Tcells@meta.data$age[grep("FS",Tcells$Sample)] <- "fetal"
Tcells@meta.data$age[grep("UCB",Tcells$Sample)] <- "cord"
Tcells@meta.data$age[grep("APB",Tcells$Sample)] <- "adult"

# Add Tcelltype
# This is dependent on both sample-assignment and 10X-lane,
# so I will need to add how samples were added to each lane
samples.4 <- c("FS3", "FS4", "FS5", "UCB1", "UCB2", "UCB5", "APB1", "APB2", "APB4", "APB5")
samples.8 <- c("FS1", "FS5", "UCB2", "UCB3", "UCB4", "UCB5", "APB2", "APB3", "APB5")
samples.48.4 <- c("FS1", "FS2", "UCB4", "UCB3", "APB3")
samples.48.8 <- c("FS3", "UCB1", "APB1", "APB4")
samples.48 <- c(samples.48.4,samples.48.8)

#For all the cells in each Lane, add the Tcelltype to a "Tcelltype" metadata
#iff the cell is assigned to a sample from its lane, and a singlet
Tcells@meta.data$Tcelltype <- NA
Tcells@meta.data$Tcelltype[(Tcells$Sample%in%samples.4) & (Tcells$Lane=="CD4")] <- "CD4"
Tcells@meta.data$Tcelltype[(Tcells$Sample%in%samples.48.4) & (Tcells$Lane=="CD4-8")] <- "CD4"
Tcells@meta.data$Tcelltype[(Tcells$Sample%in%samples.8) & (Tcells$Lane=="CD8")] <- "CD8"
Tcells@meta.data$Tcelltype[(Tcells$Sample%in%samples.48.8) & (Tcells$Lane=="CD4-8")] <- "CD8"
```

These are the sample names I am loading from Demuxlet files:
APB1801 APB1802 APB1803 APB1804 APB1805  FS1845  FS1848  FS1849  FS1850  FS1851 
   2964    2866    2850    3086    2945    3266    1690    2211    1377    3190 
SLVR007 SLVR011 SLVR018 SLVR026 SLVR063 
   2758    3124    3267    2511    2048 

Do you know what I am doing wrong?
Am I using the wrong files?

thanks, 
Francesc

**Comment by dtm2451** [comment]
Very sorry for the long delay before my response! This looks more like an erroneous file upload on my part, rather than anything you are doing wrong, so I very much apologize for that as well!

I must not have updated these .best files after we updated the sample names for publication,  but I'd rather not give the conversion key (just to keep that extra layer of work/separation for patient privacy compared to the IDs you are seeing). Instead, I've re-uploaded these data to figshare with the proper .best files.

Please re-download and try again!
